#Made with help from https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139
sudo: false

language: go

go:
  - 1.10.x

install:
  - go get ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...


notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash) -F unittests